services:

  app_proxy:
    environment:
      APP_HOST: csadv-waha_web_1
      APP_PORT: 3000

  web:
    image: devlikeapro/waha:latest
    restart: unless-stopped
    user: "0:0"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - WAHA_SERVER_HOST=0.0.0.0
      - WAHA_SERVER_PORT=3000
      - WHATSAPP_SWAGGER_USERNAME=user
      - WHATSAPP_SWAGGER_PASSWORD=pass
      - WAHA_API_KEY=api_key
      - WAHA_DASHBOARD_USERNAME=user
      - WAHA_DASHBOARD_PASSWORD=pass
    volumes:
      - ${APP_DATA_DIR}/data/sessions:/app/.sessions
      - ${APP_DATA_DIR}/data/media:/app/.media

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=tunnel_token
    depends_on:
      - web
