#!/usr/bin/env bash

export APP_DATA_DIR="${APP_DATA_DIR}"
export OLLAMA_BASE_URL="${OLLAMA_BASE_URL}"
export WAHA_API_KEY="${WAHA_API_KEY}"
export DASHBOARD_USERNAME="${DASHBOARD_USERNAME}"
export DASHBOARD_PASSWORD="${DASHBOARD_PASSWORD}"
export SWAGGER_USERNAME="${SWAGGER_USERNAME}"
export SWAGGER_PASSWORD="${SWAGGER_PASSWORD}"
